hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh!
hhhhhhhhhhhhhhhhhhhhhhhhhhhhh!
hhhhhhh!!
hhh!e

hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh!p

rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr!
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh!
rrrrrrrrrrrrrrrrrr!
rr!
hhhhhhhhhhhhhhhhhh!

rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr!

hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh!
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh!
h!
rr!
rrrrrrrrrrrrrrrrr!
hhh!
rrr!e
h!




